"""Preset topic definitions: tickers, search keywords, and section labels."""

PRESET_TOPICS = {
    "exchange_rate": {
        "key": "exchange_rate",
        "label": "환율",
        "description": "USD/KRW 환율 전망 및 주요 통화 분석",
        "fred_series": ["FEDFUNDS", "UNRATE", "CPIAUCSL", "DGS10", "T10Y2Y"],
        "bok_series": ["722Y001", "301Y013", "732Y004"],
        "tickers": {
            "USDKRW=X": "USD/KRW",
            "USDJPY=X": "USD/JPY",
            "EURUSD=X": "EUR/USD",
            "DX-Y.NYB": "DXY (달러인덱스)",
            "^TNX": "미국 10년물 금리",
            "^VIX": "VIX",
            "GC=F": "금",
            "CL=F": "WTI 원유",
            "^KS11": "KOSPI",
        },
        "search_keywords": ["환율", "원화", "달러", "KRW", "USD", "BOK", "한국은행", "Fed", "FOMC", "엔화", "JPY", "DXY", "외환"],
        "memory_keywords": ["환율", "원화", "달러", "금리", "fed", "bok", "fx", "krw", "dollar"],
        "theme_axes": [
            "미국 금리와 달러 방향 — 금리가 어디로 가는지, 달러 강세가 이어지는지",
            "에너지 수입과 경상수지 — 유가가 오르면 원화에 어떤 영향을 주는지",
            "한국 통화정책 경로 — 한국은행이 금리를 언제 어떻게 바꿀지",
            "외국인 자금 흐름 — 해외 투자자가 한국 자산을 사고 있는지 팔고 있는지",
        ],
        "report_type": "macro_analysis",
        "report_sections": [
            "핵심 결론",
            "데이터 한눈에 보기",
            "지금 어떤 상황인가",
            "앞으로 어떻게 될까",
            "무엇을 지켜볼까",
            "결론",
        ],
        "history_period": "3y",
    },
    "interest_rate": {
        "key": "interest_rate",
        "label": "금리",
        "description": "미국·한국 금리 환경 및 수익률 곡선 분석",
        "fred_series": ["FEDFUNDS", "DGS10", "DGS2", "T10Y2Y", "CPIAUCSL"],
        "bok_series": ["722Y001", "731Y003"],
        "tickers": {
            "^TNX": "미국 10년물",
            "^TYX": "미국 30년물",
            "^FVX": "미국 5년물",
            "^IRX": "미국 13주 T-bill",
            "TLT": "장기채 ETF",
            "IEF": "중기채 ETF",
            "HYG": "하이일드 ETF",
            "LQD": "IG 회사채 ETF",
            "DX-Y.NYB": "DXY",
            "^VIX": "VIX",
        },
        "search_keywords": ["금리", "Fed", "FOMC", "한국은행", "BOK", "국채", "채권", "yield", "수익률", "인상", "인하", "통화정책", "CPI", "인플레이션"],
        "memory_keywords": ["금리", "fed", "fomc", "bok", "국채", "채권", "rate", "yield", "인플레이션", "통화정책"],
        "theme_axes": [
            "미국 중앙은행(Fed) 정책 방향 — 금리를 올릴지, 내릴지, 유지할지",
            "물가(인플레이션) 흐름 — 물가가 잡히고 있는지 아닌지",
            "단기·장기 금리 관계 — 단기 금리가 장기 금리보다 높은 비정상 상태인지",
            "회사채 시장 — 기업들이 돈 빌리는 비용이 어떻게 변하는지",
            "한국 금리와 한국은행 정책",
        ],
        "report_type": "macro_analysis",
        "report_sections": [
            "핵심 결론",
            "데이터 한눈에 보기",
            "지금 어떤 상황인가",
            "앞으로 어떻게 될까",
            "무엇을 지켜볼까",
            "결론",
        ],
        "history_period": "3y",
    },
    "earnings": {
        "key": "earnings",
        "label": "기업실적",
        "description": "어닝시즌 동향 및 섹터별 실적 분석",
        "fred_series": ["UNRATE", "PAYEMS", "CPIAUCSL", "INDPRO"],
        "bok_series": [],
        "tickers": {
            "SPY": "S&P 500",
            "QQQ": "Nasdaq 100",
            "XLK": "테크 섹터",
            "XLF": "금융 섹터",
            "XLE": "에너지 섹터",
            "XLV": "헬스케어 섹터",
            "XLI": "산업재 섹터",
            "^KS11": "KOSPI",
            "^KQ11": "KOSDAQ",
            "^VIX": "VIX",
        },
        "search_keywords": ["실적", "earnings", "EPS", "revenue", "가이던스", "guidance", "어닝", "순이익", "매출", "분기", "컨센서스", "beat", "miss"],
        "memory_keywords": ["실적", "earnings", "eps", "revenue", "가이던스", "어닝"],
        "theme_axes": [
            "S&P 500 전반적 실적 흐름 — 기업들이 예상보다 잘하고 있는지 못하고 있는지",
            "주요 업종별 성과 — 어느 업종이 잘 버는지, 어느 업종이 어려운지",
            "한국 기업 영향 — 미국 실적 흐름이 국내 기업에 어떻게 연결되는지",
            "주가 수준(밸류에이션) — 실적 대비 주가가 비싼지 싼지",
            "다음에 주목할 실적 발표",
        ],
        "report_type": "earnings_analysis",
        "report_sections": [
            "핵심 결론",
            "데이터 한눈에 보기",
            "지금 어떤 상황인가",
            "앞으로 어떻게 될까",
            "무엇을 지켜볼까",
            "결론",
        ],
        "history_period": "1y",
    },
    "weekly_market": {
        "key": "weekly_market",
        "label": "주간 시황",
        "description": "주간 시장 흐름 요약 및 다음 주 주목 이벤트",
        "fred_series": ["FEDFUNDS", "UNRATE", "DGS10"],
        "bok_series": ["722Y001"],
        "tickers": {
            "SPY": "S&P 500",
            "QQQ": "Nasdaq 100",
            "IWM": "Russell 2000",
            "^KS11": "KOSPI",
            "^KQ11": "KOSDAQ",
            "DX-Y.NYB": "DXY",
            "^TNX": "미국 10년물",
            "^VIX": "VIX",
            "GC=F": "금",
            "CL=F": "WTI",
        },
        "search_keywords": ["주간", "weekly", "시장", "market", "지수", "KOSPI", "S&P", "Nasdaq", "섹터", "수급", "외국인"],
        "memory_keywords": ["주간", "시장", "market", "kospi", "s&p", "nasdaq", "지수"],
        "theme_axes": [
            "주식 시장 전반 흐름 — 지수가 오른 이유, 내린 이유, 어떤 종목이 이끌었는지",
            "금리와 달러 환경 — 이번 주 금리·환율이 시장에 어떤 영향을 줬는지",
            "에너지·원자재 — 유가와 원자재 가격이 어디로 움직였는지",
            "시장 분위기 (변동성) — 투자자들이 불안해하고 있는지 여유 있는지",
            "한국 시장 특이사항 — KOSPI·KOSDAQ의 이번 주 포인트",
        ],
        "report_type": "weekly_summary",
        "report_sections": [
            "핵심 결론",
            "데이터 한눈에 보기",
            "지금 어떤 상황인가",
            "앞으로 어떻게 될까",
            "무엇을 지켜볼까",
            "결론",
        ],
        "history_period": "3mo",
    },
    "industry_trend": {
        "key": "industry_trend",
        "label": "산업 동향",
        "description": "주요 산업·섹터별 흐름 및 테마 분석",
        "fred_series": ["INDPRO", "UNRATE", "CPIAUCSL", "DGS10"],
        "bok_series": [],
        "tickers": {
            "XLK": "테크 섹터",
            "XLF": "금융 섹터",
            "XLE": "에너지 섹터",
            "XLV": "헬스케어 섹터",
            "XLI": "산업재 섹터",
            "XLY": "소비재 섹터",
            "XLC": "커뮤니케이션 섹터",
            "SOXX": "반도체",
            "^KS11": "KOSPI",
            "^VIX": "VIX",
        },
        "search_keywords": ["산업", "섹터", "sector", "반도체", "AI", "에너지", "헬스케어", "테크", "industry", "테마", "공급망", "수요"],
        "memory_keywords": ["산업", "섹터", "sector", "반도체", "ai", "테크", "에너지", "헬스케어", "공급망"],
        "theme_axes": [
            "주요 섹터 성과 비교 — 어느 업종이 강하고 어느 업종이 약한지, 그 이유",
            "핵심 산업 트렌드 — AI·반도체·에너지 등 지금 가장 주목받는 흐름",
            "공급망과 원자재 — 공급 병목이나 원자재 가격이 산업에 미치는 영향",
            "규제와 정책 — 각국 정부 정책이나 규제가 특정 업종에 어떤 영향을 주는지",
            "한국 산업 연결 — 글로벌 흐름이 국내 주요 수출 산업에 어떻게 연결되는지",
        ],
        "report_type": "industry_analysis",
        "report_sections": [
            "핵심 결론",
            "데이터 한눈에 보기",
            "지금 어떤 상황인가",
            "앞으로 어떻게 될까",
            "무엇을 지켜볼까",
            "결론",
        ],
        "history_period": "1y",
    },
}


def get_topic_config(topic_key, custom_label=None, custom_tickers=None):
    if topic_key == "custom":
        label = custom_label or "커스텀 주제"
        return {
            "key": "custom",
            "label": label,
            "description": label,
            "fred_series": ["FEDFUNDS", "UNRATE", "DGS10"],
            "bok_series": ["722Y001"],
            "tickers": custom_tickers or {
                "SPY": "S&P 500",
                "^KS11": "KOSPI",
                "DX-Y.NYB": "DXY",
                "^TNX": "미국 10년물",
                "^VIX": "VIX",
            },
            "search_keywords": [w for w in label.split() if len(w) > 1],
            "memory_keywords": [w.lower() for w in label.split() if len(w) > 1],
            "theme_axes": [
                f"{label}의 현재 상황 — 지금 어떤 흐름이 이어지고 있는지",
                f"{label}에 영향을 주는 주요 요인",
                "시장 전반과의 연결 — 이 주제가 주식·금리·환율과 어떻게 연결되는지",
            ],
            "report_type": "custom",
            "report_sections": [
                "핵심 결론",
                "데이터 한눈에 보기",
                "지금 어떤 상황인가",
                "앞으로 어떻게 될까",
                "무엇을 지켜볼까",
                "결론",
            ],
            "history_period": "1y",
        }
    return PRESET_TOPICS.get(topic_key) or PRESET_TOPICS["weekly_market"]
